'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,X,MessageSquareText,BookOpen,LayoutDashboard,Layers} from 'lucide-react';
export function destinationFor(text:string){
 const t=text.toLowerCase().trim();
 if(/track|status|reports|स्थिति|मेरी शिकायत|शिकायतें|रिपोर्ट देख/.test(t))return 'Citizen reports';
 if(/complaint|report|issue|शिकायत|समस्या|रिपोर्ट|shikayat/.test(t))return 'complaint';
 if(/about|help|मदद|जानकारी|कैसे/.test(t))return 'about';
 if(/project|plan|budget|योजना|बजट/.test(t))return 'Project planner';
 if(/impact|evidence|प्रभाव|सबूत/.test(t))return 'Impact & evidence';
 if(/home|overview|map|होम|मुख्य|नक्शा/.test(t))return 'Overview';
 return null;
}
export default function VoiceNavigator({onNavigate,authority=false}:{authority?:boolean,onNavigate:(s:string)=>void}){
 const [open,setOpen]=useState(false),[lang,setLang]=useState('hi-IN'),[listening,setListening]=useState(false),[message,setMessage]=useState('');
 const speech=useRef<any>(null);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>()=>{speech.current?.abort();window.speechSynthesis?.cancel()},[]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 function close(){speech.current?.abort();setListening(false);setOpen(false);window.speechSynthesis?.cancel()}
 function go(destination:string){if(!authority&&['Project planner','Impact & evidence'].includes(destination)){setMessage('यह सुविधा सरकारी इंटरफ़ेस में है। Planning is available in the Government authority interface.');return}close();onNavigate(destination);const words:Record<string,string>={complaint:'शिकायत का पेज खुल गया।',about:'मदद का पेज खुल गया।','Citizen reports':'शिकायतों की सूची खुल गई।',Overview:'मुख्य पेज खुल गया।','Project planner':'योजना का पेज खुल गया।','Impact & evidence':'प्रभाव और सबूत का पेज खुल गया।'};if('speechSynthesis' in window){const utterance=new SpeechSynthesisUtterance(lang==='hi-IN'?words[destination]:'Opened '+(destination==='complaint'?'the complaint form':destination));utterance.lang=lang;window.speechSynthesis.speak(utterance)}}
 function listen(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setMessage('इस ब्राउज़र में आवाज़ उपलब्ध नहीं है। नीचे बड़ा बटन दबाएं। Voice is unavailable here. Please use a shortcut below.');return}const recognition=new SR();speech.current=recognition;recognition.lang=lang;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=(e:any)=>{const text=e.results[0][0].transcript;const destination=destinationFor(text);if(destination)go(destination);else setMessage('“'+text+'” — समझ नहीं आया। फिर बोलें या नीचे बटन चुनें। Please try again or choose a shortcut.')};recognition.onend=()=>setListening(false);recognition.onerror=(e:any)=>{setListening(false);setMessage(e.error==='not-allowed'?'माइक्रोफ़ोन की अनुमति नहीं मिली। नीचे बटन चुनें। Microphone permission was denied. Use a shortcut below.':'आवाज़ नहीं मिली। फिर कोशिश करें या बटन चुनें। Could not hear you. Try again or tap below.')};setMessage('');try{recognition.start();setListening(true)}catch{setListening(false);setMessage('Please try again or use a shortcut below. नीचे बटन चुनें।')}}
 return <><button className="voice-launch" onClick={()=>{setOpen(true);setMessage('')}}><span className="voice-symbol"><Mic size={28}/></span><span><strong>बोलकर खोलें <span>/ Speak to navigate</span></strong><small>शिकायत करने के लिए यहाँ दबाएं · Tap here for voice help</small></span></button><dialog ref={dialog} className="voice-dialog" onCancel={close}><div className="modal-head"><h2>कहाँ जाना है? / Where would you like to go?</h2><button onClick={close} aria-label="Close voice navigation"><X/></button></div><div className="modal-body"><p>“शिकायत दर्ज करें” बोलें<br/>Say “Open complaint”</p><label>भाषा / Language<select value={lang} disabled={listening} onChange={e=>setLang(e.target.value)}><option value="hi-IN">हिन्दी</option><option value="en-IN">English</option></select></label><button className="primary full listen-button" onClick={listening?()=>speech.current?.stop():listen}><Mic size={26}/>{listening?'सुन रहे हैं… रोकें / Stop listening':'बोलना शुरू करें / Start speaking'}</button><p className="voice-status" role="status" aria-live="polite">{message||(listening?'अब बोलें / Speak now':'एक बटन दबाकर भी खोल सकते हैं / Or tap a shortcut')}</p><div className="voice-shortcuts">{[['complaint','शिकायत दर्ज करें','Make a complaint',MessageSquareText],['Citizen reports','शिकायतें देखें','View complaints',MessageSquareText],['Overview','मुख्य पेज','Overview',LayoutDashboard],['Project planner','योजना देखें','Project planner',Layers],['about','मदद / जानकारी','About & help',BookOpen]].filter(([id])=>authority||id!=='Project planner').map(([id,hi,en,Icon]:any)=><button key={id} onClick={()=>go(id)}><Icon size={24}/><span>{hi}<small>{en}</small></span></button>)}</div><p className="fine">Microphone starts only when you tap Start speaking. Speech recognition uses your browser’s service and may need internet. Navigation never submits a complaint.</p></div></dialog></>
}
