const kanpurAreas=[
{id:'govind',name:'Govind Nagar',lat:26.450,lng:80.305,households:420,gap:90,critical:100,cost:4.2,project:'Restore the school approach drain',detail:'Desilt 280 m of roadside drains and restore the blocked outlet near the school approach.',reports:18},
{id:'kidwai',name:'Kidwai Nagar',lat:26.437,lng:80.331,households:360,gap:80,critical:75,cost:3.6,project:'Reconnect the neighbourhood outfall',detail:'Clear the disconnected outfall and repair 180 m of damaged drain lining.',reports:14},
{id:'kakadeo',name:'Kakadeo',lat:26.482,lng:80.285,households:280,gap:65,critical:50,cost:2.8,project:'Clear the market drainage corridor',detail:'Remove silt and waste from 220 m of the market-side drainage corridor.',reports:11},
{id:'swaroop',name:'Swaroop Nagar',lat:26.485,lng:80.316,households:190,gap:45,critical:40,cost:2.4,project:'Repair roadside drain covers',detail:'Replace damaged covers and clear the junction to restore pedestrian access.',reports:8},
{id:'jajmau',name:'Jajmau',lat:26.432,lng:80.402,households:510,gap:95,critical:80,cost:5.8,project:'Restore the residential drainage link',detail:'Survey and rehabilitate 360 m of the residential link drain.',reports:7},
{id:'civil',name:'Civil Lines',lat:26.477,lng:80.350,households:140,gap:35,critical:30,cost:1.8,project:'Desilt the lane collection drain',detail:'Routine desilting and outlet inspection along 120 m of residential lane.',reports:6}];
export const districts='Agra|Aligarh|Ambedkar Nagar|Amethi|Amroha|Auraiya|Ayodhya|Azamgarh|Baghpat|Bahraich|Ballia|Balrampur|Banda|Barabanki|Bareilly|Basti|Bhadohi|Bijnor|Budaun|Bulandshahr|Chandauli|Chitrakoot|Deoria|Etah|Etawah|Farrukhabad|Fatehpur|Firozabad|Gautam Buddha Nagar|Ghaziabad|Ghazipur|Gonda|Gorakhpur|Hamirpur|Hapur|Hardoi|Hathras|Jalaun|Jaunpur|Jhansi|Kannauj|Kanpur Dehat|Kanpur Nagar|Kasganj|Kaushambi|Kheri|Kushinagar|Lalitpur|Lucknow|Maharajganj|Mahoba|Mainpuri|Mathura|Mau|Meerut|Mirzapur|Moradabad|Muzaffarnagar|Pilibhit|Pratapgarh|Prayagraj|Raebareli|Rampur|Saharanpur|Sambhal|Sant Kabir Nagar|Shahjahanpur|Shamli|Shravasti|Siddharthnagar|Sitapur|Sonbhadra|Sultanpur|Unnao|Varanasi'.split('|');
const regionalDemos=[
{id:'lucknow',district:'Lucknow',name:'Alambagh',lat:26.812,lng:80.901},
{id:'varanasi',district:'Varanasi',name:'Lanka',lat:25.282,lng:83.002},
{id:'agra',district:'Agra',name:'Kamla Nagar',lat:27.214,lng:78.019},
{id:'gorakhpur',district:'Gorakhpur',name:'Rustampur',lat:26.731,lng:83.374},
{id:'meerut',district:'Meerut',name:'Shastri Nagar',lat:28.962,lng:77.733}
].map((a,i)=>({...a,households:200+i*40,gap:60+i*5,critical:50+i*5,cost:2.5+i*.5,project:'Restore the residential drainage outlet',detail:'Illustrative proposal: inspect and clear the residential drainage outlet. Verify scope and cost in the field.',reports:5+i}));
export const areas=[...kanpurAreas.map(a=>({...a,district:'Kanpur Nagar'})),...regionalDemos,...districts.map((district,i)=>({id:'district-'+i,district,name:district+' · Other locality',lat:0,lng:0,households:0,gap:0,critical:0,cost:0,project:'Field assessment required',detail:'This district accepts reports. Mapping, exposure and cost estimates require a local field assessment.',reports:0}))];
export type Report={id:string,area:string,description:string,category:string,severity:number,status:string,created:string,language:string,source:string};
export type Decision={id:string,area:string,status:string,note:string,created:string};
export const seed:Report[]=areas.flatMap((a,i)=>Array.from({length:a.reports},(_,j)=>({id:`DEMO-${i+1}${String(j+1).padStart(2,'0')}`,area:a.id,description:j%3===0?'बारिश के बाद नाली का पानी सड़क पर भर जाता है। कृपया सफाई कराएं।':j%3===1?'The roadside drain is blocked. Water remains in the lane after rainfall.':i===0?'Waterlogging blocks access to the school. Children have to walk through dirty water.':'The drain outlet needs inspection. Water is collecting near our homes.',category:j%3===2?'Waterlogging':'Blocked drain',severity:i===0?3:i<3?2:1,status:j===0?'Resolved':j===1?'In review':'Received',created:new Date(Date.UTC(2026,8,28-j%7,8+i,j)).toISOString(),language:j%3===0?'Hindi':'English',source:'Demo'})));
export function analyse(text:string){const critical=/school|hospital|electric|स्कूल|विद्यालय|अस्पताल|बिजली|children/i.test(text);const known=/drain|water|flood|sewage|नाली|पानी|जलभराव|सीवर/i.test(text);return {category:/cover|ढक्कन/i.test(text)?'Broken cover':/flood|waterlog|जलभराव|भर/i.test(text)?'Waterlogging':'Blocked drain',severity:critical?3:known?2:1,summary:text,engine:'Built-in rules',review:!known?'Needs clarification':critical?'Urgent field verification':'Field verification recommended'};}
export function ranked(reports:Report[]){return areas.filter(a=>a.cost>0).map(a=>{const rs=reports.filter(r=>r.area===a.id&&r.status!=='Resolved');const demand=Math.min(100,rs.length*5);const urgency=rs.length?Math.max(...rs.map(r=>r.severity))/3*100:0;const score=Math.round(demand*.25+urgency*.3+a.gap*.25+a.critical*.2);return {...a,count:rs.length,score,demand,urgency};}).sort((a,b)=>b.score-a.score);}
export function plan(projects:ReturnType<typeof ranked>,budget:number){let best:any[]=[];let value=-1;for(let mask=0;mask<1<<projects.length;mask++){const chosen=projects.filter((_,i)=>mask&(1<<i));const cost=chosen.reduce((s,a)=>s+a.cost,0);const v=chosen.reduce((s,a)=>s+a.score,0);if(cost<=budget+0.0001&&v>value){best=chosen;value=v;}}return best;}
